### ISSUE TITLE
Android - Turn on Location Service popup not coming

### ISSUE THREAD

**Issue by Android773** [Agontuk/react-native-geolocation-service#108]
Hi,

My setup is

```
"dependencies": {
    "@react-native-community/geolocation": "^1.4.2",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-geolocation-service": "^3.0.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "^3.11.1"
},
```
And code is:

```
Geolocation.getCurrentPosition(
    (position) => {
        console.warn("Position " + position.coords.latitude + " " + position.coords.longitude);
    },
    (error) => {
        // See error code charts below.
        console.warn("Error " + error.code, error.message);
    },
    { enableHighAccuracy: true, timeout: 15000, maximumAge: 10000, }
);
```

Scenario:

1. I have already added code for PermissionsAndroid and after getting the permission I am hitting the above mentioned code.
2. Android -

When the Location in top drawer menu is ON then I am getting location.

But when Location is off, it is not showing the following popup to ask user to enable the location service:

![image](https://user-images.githubusercontent.com/29795628/62203950-d079d100-b3a9-11e9-88de-63442449f5de.png)

Instead, it directly goes to (error) and says, "error.code = 2, No location provider available."

I think in earlier versions of library this used to work. But facing this problem in 3.0.0.
3. In iOS it is working fine. It is showing popup to ask for Permission for Location.

Any help on this would be appreciated.

P.S. @Agontuk Thanks for this library. We really appreciate your efforts.

**Comment by Agontuk** [comment]
You have both `@react-native-community/geolocation` & `react-native-geolocation-service` installed. Make sure you're importing the correct library in your component. I tried 3.0.0 in my example project and the dialog is showing up correctly.

On another note, remove all android related setup described in README file. It is not needed in RN60 as it'll integrate the module automatically when installed.

**Comment by Android773** [comment]
@Agontuk I understand these things.

1. Yes, my import is correct.

`import Geolocation from 'react-native-geolocation-service';`

I have added `@react-native-community/geolocation` module because when I ran it on iOS, it was asking to link this module to app, I searched about it and got to know that in RN 0.60 geolocation is removed as built in module and now is available as a separate module. And library had internal dependency on that so I had to install that as well.

a. After installing `@react-native-community/geolocation` Location is working fine on iOS.
b. On Android it wasn't working even when I had not added `@react-native-community/geolocation`

2. And yes, RS60 links the module automatically so I have not performed any manual steps mentioned in README file.

As you said it I just created a new empty project and integrated this library, but unfortunately the result is same. I am not getting popup.

```
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-geolocation-service": "^3.0.0"
},
```

```
import Geolocation from 'react-native-geolocation-service';
---
componentDidMount() {
        // Instead of navigator.geolocation, just use Geolocation.
        Geolocation.getCurrentPosition(
            (position) => {
                console.warn(position);
            },
            (error) => {
                // See error code charts below.
                console.warn(error.code, error.message);
            },
            { enableHighAccuracy: true, timeout: 15000, maximumAge: 10000 }
        );
}
```
I have mentioned the ACCESS_FINE_LOCATION in Manifest file and enabled the permission for app from settings.

**Comment by oakis** [comment]
What Android version are you using on your device when this happens?

**Comment by Android773** [comment]
@oakis I have tested on two devices with Android 8.0 and Android 7.0

**Comment by oakis** [comment]
@Android773 Can you try with Android 9? Might be a similar issue a bunch of others have been experiencing.

**Comment by Android773** [comment]
@oakis I tried with Android 9 as well, but it is not asking to turn Location Service on when Location is off.

**Comment by vjsingh96** [comment]
have you solved this issue?

**Comment by prasan2421** [comment]
Getting the same issue in Android version 9, package version 3.0.0 and RN version 0.6.4. No solutions so far.

**Comment by vjsingh96** [comment]
Which React Native version you are using?

**Comment by tobikl1** [comment]
Same for us with

"react-native": "0.60.4",
"@react-native-community/geolocation": "^1.4.2",
"react-native-geolocation-service": "^3.0.0",

Tested on an Android 9 Device

on iOS it works (when deactivating the locationService in device settings it reports back as no permission for app though)

**Comment by prasan2421** [comment]
> @prasan2421 Which React Native version you are using?

v 0.60.4

**Comment by vjsingh96** [comment]
Remove @react-native-community/geolocation": "^1.4.2", plugin and try

**Comment by tobikl1** [comment]
as stated before, that is a dependency for the plugin to work with iOS.

Is it possible this is an issue with the "@react-native-community/geolocation" plugin instead which is causing this one to show this behaviour?

**Comment by prasan2421** [comment]
> Remove @react-native-community/geolocation": "^1.4.2", plugin and try

i havent kept this plugin yet i have the issue, but im using @react-native-community/netinfo.
Did you solve this issue by removing @react-native-community/geolocation?

**Comment by Agontuk** [comment]
Guys, can anyone give me a sample project for this issue ? I am running an example with RN60 in my mobile and location popup is working fine for me. Also please provide any steps necessary to reproduce this.

**Comment by prasan2421** [comment]
> Guys, can anyone give me a sample project for this issue ? I am running an example with RN60 in my mobile and location popup is working fine for me. Also please provide any steps necessary to reproduce this.

https://github.com/prasan2421/location-test-project
Above is the link to my repo.
I've created a fresh RN project of version 0.60.4 and installed react-native-geolocation-service version 3.0.0. i have not kept any other package but the issue is still there. It looks like a bug of new react native itself.

**Comment by AliMSbaee** [comment]
I have the same issue. 
Android 9 
React Native: v0.60.4
react-native-geolocation-service: v 3.0.0

**Comment by Agontuk** [comment]
It seems like PR #68 introduced an additional check to determine whether location providers are enabled or not. If no providers are available, it'll immediately return error response instead of showing popup.

This check is needed because it enables us to request location even when location setting is set to `Device Only`.

We may need to find an alternate solution. What are your thoughts guys ?

**Comment by prasan2421** [comment]
so will this issue be fixed? i was also wondering how few others above managed to make this working.

**Comment by Agontuk** [comment]
Guys, let me know if this flow makes sense. Looping in @cladjules since he implemented the `forceRequestLocation` feature.

1) If location settings are ok, it'll invoke success callback with location
2) If not ok and `showLocationDialog` is `false`, it'll invoke error callback with code`SETTINGS_NOT_SATISFIED`.
3) If not ok and `showLocationDialog` is `true`, it'll show location popup to improve location accuracy.
4) If user clicks `OK`, it'll update the location settings and invoke success callback with location.
5) If user clicks `NO THANKS` and `forceRequestLocation` is `false`, it'll invoke error callback with code`SETTINGS_NOT_SATISFIED`.
6) If user clicks `NO THANKS` and `forceRequestLocation` is `true` but location provider is not enabled,  it'll invoke error callback with code `POSITION_UNAVAILABLE`.
7) If user clicks `NO THANKS` and `forceRequestLocation` is `true` and location provider is enabled,  it'll invoke success callback with location if it's possible.

**Comment by oakis** [comment]
@Agontuk Sounds good to me.

**Comment by duytq94** [comment]
I have the same problem (of course in Android)

- With RN < 0.60.0 and this library < 3.0.0. After grant permission, it will show dialog request to turn on GPS and then everything fine.

- With RN >= 0.60.0 and this library >= 3.0.0. After grant permission, it won't show dialog request to turn on GPS and throw error `message: 'No location provider available.', code: 2`. So I have to turn on GPS manually on the device.

- And about `@react-native-community/geolocation`, we have to install it for iOS working, but I think the issue won't relative to this geolocation since when I haven't installed it, the issue still happens on Android.

Did anyone get any solution? Thanks.

**Comment by Agontuk** [comment]
Fixed in `3.1.0`

**Comment by duytq94** [comment]
Everything's fine, thanks to @Agontuk

**Comment by Android773** [comment]
@Agontuk Great!

It is working fine after updating to 3.1.0.

Thanks a lot.

**Comment by gvankeerberghen** [comment]
> Guys, let me know if this flow makes sense. Looping in @cladjules since he implemented the `forceRequestLocation` feature.
> 
> 1. If location settings are ok, it'll invoke success callback with location
> 2. If not ok and `showLocationDialog` is `false`, it'll invoke error callback with code`SETTINGS_NOT_SATISFIED`.
> 3. If not ok and `showLocationDialog` is `true`, it'll show location popup to improve location accuracy.
> 4. If user clicks `OK`, it'll update the location settings and invoke success callback with location.
> 5. If user clicks `NO THANKS` and `forceRequestLocation` is `false`, it'll invoke error callback with code`SETTINGS_NOT_SATISFIED`.
> 6. If user clicks `NO THANKS` and `forceRequestLocation` is `true` but location provider is not enabled,  it'll invoke error callback with code `POSITION_UNAVAILABLE`.
> 7. If user clicks `NO THANKS` and `forceRequestLocation` is `true` and location provider is enabled,  it'll invoke success callback with location if it's possible.

@Agontuk, @cladjules : this works as intended, in my case I have the options
```js
{
  enableHighAccuracy: true,
  timeout: 15000,
  maximumAge: 1000 * 60 * 3,
  forceRequestLocation: true,
  showLocationDialog: true,
}
```
and I see the dialogue about improving location by activating Location Services, I can answer 'No, thanks' and I still get a location! Thanks for the work btw.

This is great because I do have a few users for whom activating the Google Location Services isn't an option but many others for whom it's fine.

However, for users without these Google Location Services, it seems the dialogue will show every single time my app needs to grab the location. Which might quickly become annoying for them since the main interaction in my app makes the app ask for the current location.

Is that the way you guys deliver this or did I miss some way to be more user-friendly? By only showing that dialogue once and remembering to force without dialogue afterwards for instance?

**Comment by fabripeco** [comment]
Hi!

Using `react-native-geolocation-service@4.0.0` (react-native 0.61.3 Android 6), calling
`Geolocation.watchPosition(successCb, errorCb, {
                 enableHighAccuracy: true,
                 interval: 20000,
                 showLocationDialog: true,
                 useSignificantChanges: true,
})`

the location dialog doesn't appear if the GPS is off and it results in error callback {"code": 2, "message": "No location provider available."}.
The dialog appears calling getCurrentPosition instead.
Is it the right behaviour? Should I call getCurrentPosition and afterwards watchPosition? 

Thank you!

**Comment by oakis** [comment]
@fabripeco Check for permissions first I guess https://facebook.github.io/react-native/docs/permissionsandroid

**Comment by fabripeco** [comment]
No, I get the necessary permission before calling watchPosition. Actually when I call getCurrentPosition, the location dialog is shown and GPS is turned on when I click Ok. The problem raises only with watchPosition and GPS turned off.

**Comment by millisande** [comment]
I get this issue using Android Studio Emulator of a Pixel 2 API 30 using Android 10.0+ and having chosen in my location settings to "Ask every time". It always triggers the error callback. Is this specific to using an emulator?

**Comment by betoharres** [comment]
> I get this issue using Android Studio Emulator of a Pixel 2 API 30 using Android 10.0+ and having chosen in my location settings to "Ask every time". It always triggers the error callback. Is this specific to using an emulator?

I'm also having this issue on Android 10.0 API 29 on a Nexus S emulator. And even trying to set force to true is not making the pop up to show. 
Any idea?

**Comment by Agontuk** [comment]
> I get this issue using Android Studio Emulator of a Pixel 2 API 30 using Android 10.0+ and having chosen in my location settings to "Ask every time". It always triggers the error callback. Is this specific to using an emulator?

Unable to reproduce this, using the same emulator. Can you provide reproducible steps ?

**Comment by Deepak13312** [comment]
**React Native iOS**
    ***As you can see my code that the location popup permission is not showing in iOS, while I am using "react-native-geolocatio-service". I am struggling with, please help me, it would be more appreciable.****
        
            onPressLocation = () => {
                var that = this;
                async function requestLocationPermission() {
                  const options = {
                    maxWidth: 500,
                    maxHeight: 500,
                    storageOptions: {
                      skipBackup: true,
                    },
                  };
                  const granted = await PermissionsAndroid.request(
                    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
                    {
                      title: 'ThoughtBulb App location Permission',
                      message: 'ThoughtBulb App needs access to your location ',
                    },
                  );
                  if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                    Geolocation.getCurrentPosition(
                      position => {
                        const currentLongitude = JSON.stringify(position.coords.longitude);
                        const currentLatitude = JSON.stringify(position.coords.latitude);
                        that.setState({
                          currentLatitude: currentLatitude,
                          currentLongitude: currentLongitude,
                        });
                      },
                      error => {
                        console.log(error);
                      },
                      {enableHighAccuracy: true, timeout: 15000, maximumAge: 10000},
                    );
                  } else {
                    alert('Location Permission is denied.');
                  }
                }
                if (Platform.OS === 'android') {
                  requestLocationPermission();
                } else {
        *****Here I need to get iOS location permission popup before execute below funtion.
    I think this issue raised after updated the Xcode from 10 to 12***
                  Geolocation.getCurrentPosition(
                    position => {
                      const currentLongitude = JSON.stringify(position.coords.longitude);
                      const currentLatitude = JSON.stringify(position.coords.latitude);
                      that.setState({
                        currentLatitude: currentLatitude,
                        currentLongitude: currentLongitude,
                      });
                    },
                    error => {
                      console.log(error);
                    },
                    {enableHighAccuracy: true, timeout: 15000, maximumAge: 10000},
                  );
                }
              };

**Comment by ivanovyoan** [comment]
@Deepak13312 also have the same problem, haven't found a solution to it.

**Comment by reggi49** [comment]
> @Deepak13312 also have the same problem, haven't found a solution to it.

mungkin ini sedikit membantu, pertama pastikan tidak ada library lokasi lain selain react-native-geolocation-service. selanjutnya jika ada tidak memakai react hook. anda mungkin bisa mencoba cara dibawah

`hasLocationPermission = async () => {
    const hasPermission = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
    );

    if (hasPermission === PermissionsAndroid.RESULTS.GRANTED) {
      console.log('lagi req permission');
      return true;
    }

    const status = await PermissionsAndroid.check(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
    );

    if (status) {
      console.log('permission diberikan');
      return true;
    }

    if (status === PermissionsAndroid.RESULTS.DENIED) {
      ToastAndroid.show(
        'Location permission denied by user.',
        ToastAndroid.LONG,
      );
    } else if (status === PermissionsAndroid.RESULTS.NEVER_ASK_AGAIN) {
      ToastAndroid.show(
        'Location permission revoked by user.',
        ToastAndroid.LONG,
      );
    }

    return false;
  };`

`async componentDidMount() {
    if (await this.hasLocationPermission()) {
    Geolocation.getCurrentPosition(
        position => {
          // this.fetchNearby(position.coords.latitude, position.coords.longitude);
          // console.log(position);
          console.log('posisi ditemukan',position.coords.latitude, position.coords.longitude);
          this.setState({
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
            error: null,
          });
          this.goToRegion(position.coords.latitude, position.coords.longitude);
        },
        error => {
          Alert.alert(
            'Oopss!',
            error.message,
            [
              {
                text: 'OK',
                onPress: () => console.log('Cancel Pressed'),
              },
            ],
          );
          console.log(error.message);
          this.setState({error: error.message});
        },
        {
          accuracy: {
            android: 'high',
            ios: 'best',
          },
          enableHighAccuracy: true,
          timeout: 15000,
          maximumAge: 10000,
          distanceFilter: 0,
          forceRequestLocation: true,
          forceLocationManager: false,
          showLocationDialog: true,
        },
      );
    }
  }`

**Comment by RajuPedimalla** [comment]
Can anyone help me on this ?
I am facing the same issue, Unable to show the Prompt to the users. Its going into the else statement and giving error code and saying **No location provider available**


const result = Functions.getInstance().requestLocationPermission();
        result.then(res => {
          if (res) {
              Geolocation.getCurrentPosition(
                position => {
                  const latitude = position.coords.latitude;
                  const longitude = position.coords.longitude;
                },
                error => {
                  console.log("Error getting geolocation: " + error.code, error.message);
                },
                { timeout: 15000, forceRequestLocation: true,showLocationDialog: true,}
              );
            }
          }
          
        });
